### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/allison#4]
## Diacritics
- [ ] Diacritics need to be balanced (weight, size, contrast). Please ensure the definitive design is adjusted in the combining marks, so they will be ready to create the compound glyphs.
- [ ] Caron.alt need to have the alternate shape used in `Ľ` [Slovak](https://en.wikipedia.org/wiki/%C4%BD)
- [ ] Leave a 0 sidebearings value for the marks

![Allison-diacs](https://user-images.githubusercontent.com/48698976/121546407-e0649200-c9d0-11eb-8f77-65a7d50fe788.png)

![Allison-diacs-2](https://user-images.githubusercontent.com/48698976/121548420-9bd9f600-c9d2-11eb-848b-035b20f7b15d.png)

![Screen Shot 2021-06-10 at 09 56 51](https://user-images.githubusercontent.com/48698976/121548573-bd3ae200-c9d2-11eb-8338-b76ad42a69f4.png)
![Screen Shot 2021-06-10 at 10 00 37](https://user-images.githubusercontent.com/48698976/121548575-bdd37880-c9d2-11eb-96e3-5027e93642aa.png)

**Comment by vv-monsalve** [comment]
@RobLeuschke This is the new needed job on diacritics

**Comment by vv-monsalve** [comment]
## Google Fonts Latin Plus coverage

- [ ] Design all the glyphs required in the [GF Latin Plus encoding](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/plus_unique-glyphs.txt)
- [ ] Create all the comb marks as mentioned above
- [ ] Leave only the compound glyphs marked in dark grey as pending to be created using the components

**Comment by RobLeuschke** [comment]
I have completed all three tasks above.

**Comment by vv-monsalve** [comment]
> I have completed all three tasks above.

Thanks Rob. We'll work on the files and let you know if anything else emerges.

**Comment by vv-monsalve** [comment]
@crystaltype from our conversation, these are the spotted cases to fix

<img width="192" alt="Screen Shot 2021-06-29 at 08 55 09" src="https://user-images.githubusercontent.com/48698976/123812974-25863080-d8ba-11eb-9c04-f035794c0fe0.png">
<img width="143" alt="Screen Shot 2021-06-29 at 08 55 14" src="https://user-images.githubusercontent.com/48698976/123812986-26b75d80-d8ba-11eb-88b7-39c555aecd9e.png">
<img width="110" alt="Screen Shot 2021-06-29 at 08 55 17" src="https://user-images.githubusercontent.com/48698976/123812994-274ff400-d8ba-11eb-9743-0acc53ab8944.png">
<img width="217" alt="Screen Shot 2021-06-29 at 08 55 36" src="https://user-images.githubusercontent.com/48698976/123812998-27e88a80-d8ba-11eb-9b84-a93743ca03b1.png">
<img width="139" alt="Screen Shot 2021-06-29 at 08 58 02" src="https://user-images.githubusercontent.com/48698976/123813000-28812100-d8ba-11eb-920c-e3e1147101e4.png">
<img width="140" alt="Screen Shot 2021-06-29 at 08 58 06" src="https://user-images.githubusercontent.com/48698976/123813002-2919b780-d8ba-11eb-8f29-f19e06e2ad56.png">

**Comment by RobLeuschke** [comment]
Just to be on the safe side and to clarify: I was asked not to touch Allison. So, I assume there is nothing for me to address?
Let me know if there is, please.
Thanks!

**Comment by vv-monsalve** [comment]
> Just to be on the safe side and to clarify: I was asked not to touch Allison. So, I assume there is nothing for me to address?
> Let me know if there is, please.
> Thanks!

Hi @RobLeuschke, yes as we talked the main idea is if I tag @crystaltype  it's something that she is going to take care of, and if I tag you, it's something for you to take care of.

**Comment by crystaltype** [comment]
I've solved those problems in the lastest commits, also spotted some more:
<img width="60" alt="Screen Shot 2021-07-01 at 15 05 19" src="https://user-images.githubusercontent.com/20129845/124089365-0932f100-da7e-11eb-8d86-a64d4739ef94.png">
<img width="221" alt="Screen Shot 2021-07-01 at 14 58 31" src="https://user-images.githubusercontent.com/20129845/124089376-0b954b00-da7e-11eb-8426-49b1f99a5948.png">

**Comment by RobLeuschke** [comment]
Thank you!
